server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://149.102.135.15:3311/home4u?jdbcCompliantTruncation=false&allowMultiQueries=true
    username: home4u
    password: "howpo8-neRnif-cypwyx"

  cache:
    type: redis
  data:
    redis:
      host: 149.102.135.15
      port: 6379
      repositories:
        enabled: false

  flyway:
    enabled: true
    locations: classpath:dp/migration
    baseline-on-migrate: true

